### ISSUE TITLE
It seems that EG Construction does not work?

### ISSUE THREAD

**Issue by ze-ta** [Lcrypto/Algebraic_QC-LDPC#1]

**Comment by Lcrypto** [comment]
Matlab and C++ work both

H=H_{J}{N}, H parity-check matrix it is created by cyclically rotating all hi(X) N times (parity polynomial).
G=G_{J}{N}, G generator matrix is created by cyclically rotating all g(X) (generator polynomial).
for example 

0<= i < STANDARD LINES

{0, 1, 3, 7} --> h0(X)=1+X+X^3+X^7

{0, 4, 6, 7, 8} --> g(X)=1+X^4+X^6+X^7+X^8

**Comment by ze-ta** [comment]
> Matlab and C++ work both
> 
> H=H_{J}{N}, H parity-check matrix it is created by cyclically rotating all hi(X) N times (parity polynomial). G=G_{J}{N}, G generator matrix is created by cyclically rotating all g(X) (generator polynomial). for example
> 
> 0<= i < STANDARD LINES
> 
> {0, 1, 3, 7} --> h0(X)=1+X+X^3+X^7
> 
> {0, 4, 6, 7, 8} --> g(X)=1+X^4+X^6+X^7+X^8

Great thanks for your kind reoly. :)

**Comment by Lcrypto** [comment]
You are welcome, Ze-ta!
