### ISSUE TITLE
The EG Construction scripts seems not work?

### ISSUE THREAD

**Issue by ze-ta** [Lcrypto/Algebraic_QC-LDPC#2]
Sir, the matlab file `EG_matrix_generation.m` and `Matrix_EG.m` seems not work, could you please check again?

**Comment by Lcrypto** [comment]
Yes, it work 
just use circulant values.
similar as in eg ldpc c project. For detail read article Kou Y, Lin S, Fossorier M. Low-density parity-check codes based on finite geometries: a rediscovery and new results. IEEE Transactions on Information Theory 2001; 47(7):2711–2736.



H=H_{J}{N}, H parity-check matrix it is created by cyclically rotating all hi(X) N times.

similar for generator matrix G but using g(x) polynomial

0<= i < STANDARD LINES

{0, 1, 3, 7} --> h0(X)=1+X+X^3+X^7

{0, 4, 6, 7, 8} --> g(X)=1+X^4+X^6+X^7+X^8
